### ISSUE TITLE
Problema con indexanatar y detalle de deflactanator

### ISSUE THREAD

**Issue by gsanchez3** [nsidicarocep/Mectritas#1]
Nico: 
El indexanator tiene un problema con el parametro (variables_agrupar). Entiendo que este deberia ser optativo, ya que en caso que trabajemos con una base que tiene por ejemplo solo fecha y salario y quisieramos poner la base en el minimo salario para comparar, simplemente no podriamos hacerlo. Nos obliga si o si a agrupar por una variable y no nos da la opcion de indexar sin agrupar. Adicionalmente el help o la aclaracion de lo que hace ese parametro está mal, habria que escribirlo de nuevo.

El deflactanator tiene un problema menor con el parametro (variable_mes). Si o si la variable que el mes en la base a deflactar debe llamarse "fecha". Por tanto, el parametro esta de mas, ya que si o si hay q completarlo y dejarlo siempre igual (variable_mes="fecha"). Estaria bueno si da la opcion que la variable se llame de cualquier manera, o bien eliminar el parametro aclarando que si o si debe haber una variable llamada fecha y con formato  "YYYY-MM-DD".

Abrazo y felices vacas

**Comment by nsidicarocep** [comment]
Resuelto!

**Comment by gsanchez3** [comment]
Sigue estando mal el help del indexanator... igual es re secundario porq es para uso de nosotros nomas

**Comment by gsanchez3** [comment]
lo del parametro variable_mes en el deflactanator esta resuelto. Le podes poner cualquier nombre a la variable como mes o fecha..

**Comment by gsanchez3** [comment]
Lo del indexanator funciona bien, puedo no agruparlo por ninguna variable y funciona
