### ISSUE TITLE
Recordar agregar cuits a filtro_database

### ISSUE THREAD

**Issue by gsanchez3** [nsidicarocep/Mectritas#2]
Nico, filtro_database de mectritas elimina 43 cuits q eran antiguamente falopa. 

Te mande por discord el "filtro_total" que tiene 53 cuits. Hay 10 mas q estan dentro de ese espectro "falopa/cajas provinciales", cuando vuelvan todos de vacas podemos ver bien q cuits estamos eliminando rutinariamente y ya dejamos esto establecido.

Salute

**Comment by nsidicarocep** [comment]
Listo!!

**Comment by gsanchez3** [comment]
Esta perfecto
