### ISSUE TITLE
mectra_demografia propuesta

### ISSUE THREAD

**Issue by gsanchez3** [nsidicarocep/Mectritas#3]
Detalle muy menor, podria ponerse en mectra demografia como default que sea sexo = T, pero nacimiento = F? En general el ajuste ese de nacimiento no lo usamos nunca... ademas no entiendo lo q hace... cambia un monton los datos como salen de mergear con la base de fechas de nacimiento...

**Comment by nsidicarocep** [comment]
Te debería bardear por este issue, pero bueno como me voy te lo dejo pasar y lo hice como querías...
